# TODO: PE-7331 - Skipping e2e-test job for now - swap out the whens when we are ready to run the job
# when: << pipeline.parameters.run-integration-workflow >>
when: false
jobs:
  - e2e-init:
      context: Vercel
  - e2e-test:
      context: Vercel
      requires:
        - e2e-init
