when: << pipeline.parameters.run-embed-workflow >>
jobs:
  - embed-init
  - embed-build-production:
      requires:
        - embed-init
      filters:
        branches:
          only: /(^release.*)$/
  - embed-deploy-production-cloudflare:
      context: Audius Client
      requires:
        - embed-build-production
      filters:
        branches:
          only: /(^release.*)$/
